print("..............................................")
print("Tugas1 Kelas B")
print("..............................................")
print("Nama: Dandi Nur Faizi")
print("NPM: 21083010078")
print("..............................................")
print("Notes:")
print("..............................................")
print("Halo Dunia")
print("ini adalah skrip bash pertamaku di linux")
